use "graph.ML";
use "test/ex_graph.ML";

use "match_ctxt.ML"; (* vertex and edge matching and global context *)

use "bvertex.ML";
use "bgraph.ML";

use "coeff.ML";
use "expr.ML"; 
use "linrat_expr.ML"; 
use "rg_vertex.ML";
use "rg_graph.ML";
use "test/ex_rg_graph.ML";

use "rg_match_ctxt.ML";

use "output.ML";
use "output_dot.ML";
use "output_XML.ML";

use "controller.ML";

use "patgraph.ML";


(* 
System.use "test/ex_patgraph.ML";
System.use "rg_patgraph.ML";
*)
