
polychrome.:
	echo 'use "make_polychrome.ML";' | /home/m10mb/Desktop/Quantomatic/Quanto/polyml/bin/poly -H 200

clean:
	rm -f chromeui/polychrome.polyml-heap
	find . -type d -name .polysave | xargs rm -rf
