/* Generated By:JavaCC: Do not edit this line. SVGPathParserConstants.java */
package org.lindenb.svg.path;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SVGPathParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DOT = 1;
  /** RegularExpression Id. */
  int PLUS = 2;
  /** RegularExpression Id. */
  int MINUS = 3;
  /** RegularExpression Id. */
  int DIGIT = 4;
  /** RegularExpression Id. */
  int POSITIVE_INTEGER = 5;
  /** RegularExpression Id. */
  int SIGN = 6;
  /** RegularExpression Id. */
  int EXPONENT = 7;
  /** RegularExpression Id. */
  int FLOATING_NUMBER = 8;
  /** RegularExpression Id. */
  int EXP = 9;
  /** RegularExpression Id. */
  int MOVETO = 10;
  /** RegularExpression Id. */
  int LINEH = 11;
  /** RegularExpression Id. */
  int LINEV = 12;
  /** RegularExpression Id. */
  int LINETO = 13;
  /** RegularExpression Id. */
  int CLOSEPATH = 14;
  /** RegularExpression Id. */
  int CUBICBEZIER = 15;
  /** RegularExpression Id. */
  int SMOOTHCUBICBEZIER = 16;
  /** RegularExpression Id. */
  int QUADRATICCURVE = 17;
  /** RegularExpression Id. */
  int QUADRATICSMOOTH = 18;
  /** RegularExpression Id. */
  int ELLIPTICARC = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "<DIGIT>",
    "<POSITIVE_INTEGER>",
    "<SIGN>",
    "<EXPONENT>",
    "<FLOATING_NUMBER>",
    "<EXP>",
    "<MOVETO>",
    "<LINEH>",
    "<LINEV>",
    "<LINETO>",
    "<CLOSEPATH>",
    "<CUBICBEZIER>",
    "<SMOOTHCUBICBEZIER>",
    "<QUADRATICCURVE>",
    "<QUADRATICSMOOTH>",
    "<ELLIPTICARC>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\",\"",
  };

}
